### ISSUE TITLE
Broken things

### ISSUE THREAD

**Issue by luisotaviodesimone** [luisotaviodesimone/.files#5]
- The fonts are not installing automatically
- Some `oh-my-posh` automatic configuration
- Not automatic windows terminal configuration

**Comment by laryssonalves** [comment]
The quickest way to solve this is to switch to `MacOS` bro.

**Comment by luisotaviodesimone** [comment]
> The quickest way to solve this is to switch to `MacOS` bro.

Switched to Linux. Long live open source! 😃
